TESTS = amoadd_w\
        amoand_w\
        amomaxu_w\
        amomax_w\
        amominu_w\
        amomin_w\
        amoor_w\
        amoswap_w\
        amoxor_w\
        lrsc

all: $(TESTS)

$(TESTS):
	sh ../../run.sh $@
	sh ../../run-toolchain.sh $@
