#
# ISP RAS (http://www.ispras.ru)
#
# This ruby template was automatically generated by the MicroTESK tool
# Generation started: Fri Dec 27 11:59:27 MSK 2019
#

require_relative '../riscv_base'

class SequenceGenTemplate < RiscVBaseTemplate
  def pre
    super
    data {
      label :data
      word rand(1, 9), rand(1, 9), rand(1, 9), rand(1, 9)
      label :end_data
      space 1
    }
  end
  
  def run
    set_default_allocator FREE
    
    # Only arithmetic operations
    
    sequence {
      fadd_s f(_), f(_), f(_)      
      fadd_s f(_), f(_), f(_)      
      fadd_s f(_), f(_), f(_)      
      fadd_s f(_), f(_), f(_)      
      fadd_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsub_s f(_), f(_), f(_)      
      fsub_s f(_), f(_), f(_)      
      fsub_s f(_), f(_), f(_)      
      fsub_s f(_), f(_), f(_)      
      fsub_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fmul_s f(_), f(_), f(_)      
      fmul_s f(_), f(_), f(_)      
      fmul_s f(_), f(_), f(_)      
      fmul_s f(_), f(_), f(_)      
      fmul_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fdiv_s f(_), f(_), f(_)      
      fdiv_s f(_), f(_), f(_)      
      fdiv_s f(_), f(_), f(_)      
      fdiv_s f(_), f(_), f(_)      
      fdiv_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fmin_s f(_), f(_), f(_)      
      fmin_s f(_), f(_), f(_)      
      fmin_s f(_), f(_), f(_)      
      fmin_s f(_), f(_), f(_)      
      fmin_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fmax_s f(_), f(_), f(_)      
      fmax_s f(_), f(_), f(_)      
      fmax_s f(_), f(_), f(_)      
      fmax_s f(_), f(_), f(_)      
      fmax_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsgnj_s f(_), f(_), f(_)      
      fsgnj_s f(_), f(_), f(_)      
      fsgnj_s f(_), f(_), f(_)      
      fsgnj_s f(_), f(_), f(_)      
      fsgnj_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsgnjn_s f(_), f(_), f(_)      
      fsgnjn_s f(_), f(_), f(_)      
      fsgnjn_s f(_), f(_), f(_)      
      fsgnjn_s f(_), f(_), f(_)      
      fsgnjn_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsgnjx_s f(_), f(_), f(_)      
      fsgnjx_s f(_), f(_), f(_)      
      fsgnjx_s f(_), f(_), f(_)      
      fsgnjx_s f(_), f(_), f(_)      
      fsgnjx_s f(_), f(_), f(_)      
    }.run
    
    sequence {
      fcvt_w_s x(_), f(_), _      
      fcvt_w_s x(_), f(_), _      
      fcvt_w_s x(_), f(_), _      
      fcvt_w_s x(_), f(_), _      
      fcvt_w_s x(_), f(_), _      
    }.run
    
    sequence {
      fcvt_wu_s x(_), f(_), _      
      fcvt_wu_s x(_), f(_), _      
      fcvt_wu_s x(_), f(_), _      
      fcvt_wu_s x(_), f(_), _      
      fcvt_wu_s x(_), f(_), _      
    }.run
    
    sequence {
      feq_s x(_), f(_), f(_)      
      feq_s x(_), f(_), f(_)      
      feq_s x(_), f(_), f(_)      
      feq_s x(_), f(_), f(_)      
      feq_s x(_), f(_), f(_)      
    }.run
    
    sequence {
      flt_s x(_), f(_), f(_)      
      flt_s x(_), f(_), f(_)      
      flt_s x(_), f(_), f(_)      
      flt_s x(_), f(_), f(_)      
      flt_s x(_), f(_), f(_)      
    }.run
    
    sequence {
      fle_s x(_), f(_), f(_)      
      fle_s x(_), f(_), f(_)      
      fle_s x(_), f(_), f(_)      
      fle_s x(_), f(_), f(_)      
      fle_s x(_), f(_), f(_)      
    }.run
    
    sequence {
      fadd_d f(_), f(_), f(_)      
      fadd_d f(_), f(_), f(_)      
      fadd_d f(_), f(_), f(_)      
      fadd_d f(_), f(_), f(_)      
      fadd_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsub_d f(_), f(_), f(_)      
      fsub_d f(_), f(_), f(_)      
      fsub_d f(_), f(_), f(_)      
      fsub_d f(_), f(_), f(_)      
      fsub_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fmul_d f(_), f(_), f(_)      
      fmul_d f(_), f(_), f(_)      
      fmul_d f(_), f(_), f(_)      
      fmul_d f(_), f(_), f(_)      
      fmul_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fdiv_d f(_), f(_), f(_)      
      fdiv_d f(_), f(_), f(_)      
      fdiv_d f(_), f(_), f(_)      
      fdiv_d f(_), f(_), f(_)      
      fdiv_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fmin_d f(_), f(_), f(_)      
      fmin_d f(_), f(_), f(_)      
      fmin_d f(_), f(_), f(_)      
      fmin_d f(_), f(_), f(_)      
      fmin_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fmax_d f(_), f(_), f(_)      
      fmax_d f(_), f(_), f(_)      
      fmax_d f(_), f(_), f(_)      
      fmax_d f(_), f(_), f(_)      
      fmax_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsgnj_d f(_), f(_), f(_)      
      fsgnj_d f(_), f(_), f(_)      
      fsgnj_d f(_), f(_), f(_)      
      fsgnj_d f(_), f(_), f(_)      
      fsgnj_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsgnjn_d f(_), f(_), f(_)      
      fsgnjn_d f(_), f(_), f(_)      
      fsgnjn_d f(_), f(_), f(_)      
      fsgnjn_d f(_), f(_), f(_)      
      fsgnjn_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fsgnjx_d f(_), f(_), f(_)      
      fsgnjx_d f(_), f(_), f(_)      
      fsgnjx_d f(_), f(_), f(_)      
      fsgnjx_d f(_), f(_), f(_)      
      fsgnjx_d f(_), f(_), f(_)      
    }.run
    
    sequence {
      fcvt_w_d x(_), f(_), _      
      fcvt_w_d x(_), f(_), _      
      fcvt_w_d x(_), f(_), _      
      fcvt_w_d x(_), f(_), _      
      fcvt_w_d x(_), f(_), _      
    }.run
    
    sequence {
      fcvt_wu_d x(_), f(_), _      
      fcvt_wu_d x(_), f(_), _      
      fcvt_wu_d x(_), f(_), _      
      fcvt_wu_d x(_), f(_), _      
      fcvt_wu_d x(_), f(_), _      
    }.run
    
    sequence {
      feq_d x(_), f(_), f(_)      
      feq_d x(_), f(_), f(_)      
      feq_d x(_), f(_), f(_)      
      feq_d x(_), f(_), f(_)      
      feq_d x(_), f(_), f(_)      
    }.run
    
    sequence {
      flt_d x(_), f(_), f(_)      
      flt_d x(_), f(_), f(_)      
      flt_d x(_), f(_), f(_)      
      flt_d x(_), f(_), f(_)      
      flt_d x(_), f(_), f(_)      
    }.run
    
    sequence {
      fle_d x(_), f(_), f(_)      
      fle_d x(_), f(_), f(_)      
      fle_d x(_), f(_), f(_)      
      fle_d x(_), f(_), f(_)      
      fle_d x(_), f(_), f(_)      
    }.run
    
    sequence {
      addiw x(_), x(_), _      
      addiw x(_), x(_), _      
      addiw x(_), x(_), _      
      addiw x(_), x(_), _      
      addiw x(_), x(_), _      
    }.run
    
    sequence {
      slliw x(_), x(_), _      
      slliw x(_), x(_), _      
      slliw x(_), x(_), _      
      slliw x(_), x(_), _      
      slliw x(_), x(_), _      
    }.run
    
    sequence {
      srliw x(_), x(_), _      
      srliw x(_), x(_), _      
      srliw x(_), x(_), _      
      srliw x(_), x(_), _      
      srliw x(_), x(_), _      
    }.run
    
    sequence {
      sraiw x(_), x(_), _      
      sraiw x(_), x(_), _      
      sraiw x(_), x(_), _      
      sraiw x(_), x(_), _      
      sraiw x(_), x(_), _      
    }.run
    
    sequence {
      addw x(_), x(_), x(_)      
      addw x(_), x(_), x(_)      
      addw x(_), x(_), x(_)      
      addw x(_), x(_), x(_)      
      addw x(_), x(_), x(_)      
    }.run
    
    sequence {
      subw x(_), x(_), x(_)      
      subw x(_), x(_), x(_)      
      subw x(_), x(_), x(_)      
      subw x(_), x(_), x(_)      
      subw x(_), x(_), x(_)      
    }.run
    
    sequence {
      sllw x(_), x(_), x(_)      
      sllw x(_), x(_), x(_)      
      sllw x(_), x(_), x(_)      
      sllw x(_), x(_), x(_)      
      sllw x(_), x(_), x(_)      
    }.run
    
    sequence {
      srlw x(_), x(_), x(_)      
      srlw x(_), x(_), x(_)      
      srlw x(_), x(_), x(_)      
      srlw x(_), x(_), x(_)      
      srlw x(_), x(_), x(_)      
    }.run
    
    sequence {
      sraw x(_), x(_), x(_)      
      sraw x(_), x(_), x(_)      
      sraw x(_), x(_), x(_)      
      sraw x(_), x(_), x(_)      
      sraw x(_), x(_), x(_)      
    }.run
    
    sequence {
      addi x(_), x(_), _      
      addi x(_), x(_), _      
      addi x(_), x(_), _      
      addi x(_), x(_), _      
      addi x(_), x(_), _      
    }.run
    
    sequence {
      slti x(_), x(_), _      
      slti x(_), x(_), _      
      slti x(_), x(_), _      
      slti x(_), x(_), _      
      slti x(_), x(_), _      
    }.run
    
    sequence {
      sltiu x(_), x(_), _      
      sltiu x(_), x(_), _      
      sltiu x(_), x(_), _      
      sltiu x(_), x(_), _      
      sltiu x(_), x(_), _      
    }.run
    
    sequence {
      xori x(_), x(_), _      
      xori x(_), x(_), _      
      xori x(_), x(_), _      
      xori x(_), x(_), _      
      xori x(_), x(_), _      
    }.run
    
    sequence {
      ori x(_), x(_), _      
      ori x(_), x(_), _      
      ori x(_), x(_), _      
      ori x(_), x(_), _      
      ori x(_), x(_), _      
    }.run
    
    sequence {
      andi x(_), x(_), _      
      andi x(_), x(_), _      
      andi x(_), x(_), _      
      andi x(_), x(_), _      
      andi x(_), x(_), _      
    }.run
    
    sequence {
      slli x(_), x(_), _      
      slli x(_), x(_), _      
      slli x(_), x(_), _      
      slli x(_), x(_), _      
      slli x(_), x(_), _      
    }.run
    
    sequence {
      srli x(_), x(_), _      
      srli x(_), x(_), _      
      srli x(_), x(_), _      
      srli x(_), x(_), _      
      srli x(_), x(_), _      
    }.run
    
    sequence {
      srai x(_), x(_), _      
      srai x(_), x(_), _      
      srai x(_), x(_), _      
      srai x(_), x(_), _      
      srai x(_), x(_), _      
    }.run
    
    sequence {
      sll x(_), x(_), x(_)      
      sll x(_), x(_), x(_)      
      sll x(_), x(_), x(_)      
      sll x(_), x(_), x(_)      
      sll x(_), x(_), x(_)      
    }.run
    
    sequence {
      srl x(_), x(_), x(_)      
      srl x(_), x(_), x(_)      
      srl x(_), x(_), x(_)      
      srl x(_), x(_), x(_)      
      srl x(_), x(_), x(_)      
    }.run
    
    sequence {
      sra x(_), x(_), x(_)      
      sra x(_), x(_), x(_)      
      sra x(_), x(_), x(_)      
      sra x(_), x(_), x(_)      
      sra x(_), x(_), x(_)      
    }.run
    
    sequence {
      add x(_), x(_), x(_)      
      add x(_), x(_), x(_)      
      add x(_), x(_), x(_)      
      add x(_), x(_), x(_)      
      add x(_), x(_), x(_)      
    }.run
    
    sequence {
      sub x(_), x(_), x(_)      
      sub x(_), x(_), x(_)      
      sub x(_), x(_), x(_)      
      sub x(_), x(_), x(_)      
      sub x(_), x(_), x(_)      
    }.run
    
    sequence {
      slt x(_), x(_), x(_)      
      slt x(_), x(_), x(_)      
      slt x(_), x(_), x(_)      
      slt x(_), x(_), x(_)      
      slt x(_), x(_), x(_)      
    }.run
    
    sequence {
      sltu x(_), x(_), x(_)      
      sltu x(_), x(_), x(_)      
      sltu x(_), x(_), x(_)      
      sltu x(_), x(_), x(_)      
      sltu x(_), x(_), x(_)      
    }.run
    
    sequence {
      AND x(_), x(_), x(_)      
      AND x(_), x(_), x(_)      
      AND x(_), x(_), x(_)      
      AND x(_), x(_), x(_)      
      AND x(_), x(_), x(_)      
    }.run
    
    sequence {
      OR x(_), x(_), x(_)      
      OR x(_), x(_), x(_)      
      OR x(_), x(_), x(_)      
      OR x(_), x(_), x(_)      
      OR x(_), x(_), x(_)      
    }.run
    
    sequence {
      xor x(_), x(_), x(_)      
      xor x(_), x(_), x(_)      
      xor x(_), x(_), x(_)      
      xor x(_), x(_), x(_)      
      xor x(_), x(_), x(_)      
    }.run
    
    #sequence {
    #  vadd vr(_), vr(_), vr(_)      
    #  vadd vr(_), vr(_), vr(_)      
    #  vadd vr(_), vr(_), vr(_)      
    #  vadd vr(_), vr(_), vr(_)      
    #  vadd vr(_), vr(_), vr(_)      
    #}.run
    #
    #sequence {
    #  vsub vr(_), vr(_), vr(_)      
    #  vsub vr(_), vr(_), vr(_)      
    #  vsub vr(_), vr(_), vr(_)      
    #  vsub vr(_), vr(_), vr(_)      
    #  vsub vr(_), vr(_), vr(_)      
    #}.run
    #
    #sequence {
    #  vmul vr(_), vr(_), vr(_)      
    #  vmul vr(_), vr(_), vr(_)      
    #  vmul vr(_), vr(_), vr(_)      
    #  vmul vr(_), vr(_), vr(_)      
    #  vmul vr(_), vr(_), vr(_)      
    #}.run
    #
    #sequence {
    #  vmulh vr(_), vr(_), vr(_)      
    #  vmulh vr(_), vr(_), vr(_)      
    #  vmulh vr(_), vr(_), vr(_)      
    #  vmulh vr(_), vr(_), vr(_)      
    #  vmulh vr(_), vr(_), vr(_)      
    #}.run
    #
    #sequence {
    #  vdiv vr(_), vr(_), vr(_)      
    #  vdiv vr(_), vr(_), vr(_)      
    #  vdiv vr(_), vr(_), vr(_)      
    #  vdiv vr(_), vr(_), vr(_)      
    #  vdiv vr(_), vr(_), vr(_)      
    #}.run
    
    sequence {
      fcvt_l_d x(_), f(_), _      
      fcvt_l_d x(_), f(_), _      
      fcvt_l_d x(_), f(_), _      
      fcvt_l_d x(_), f(_), _      
      fcvt_l_d x(_), f(_), _      
    }.run
    
    sequence {
      fcvt_lu_d x(_), f(_), _      
      fcvt_lu_d x(_), f(_), _      
      fcvt_lu_d x(_), f(_), _      
      fcvt_lu_d x(_), f(_), _      
      fcvt_lu_d x(_), f(_), _      
    }.run
    
    sequence {
      fcvt_l_s x(_), f(_), _      
      fcvt_l_s x(_), f(_), _      
      fcvt_l_s x(_), f(_), _      
      fcvt_l_s x(_), f(_), _      
      fcvt_l_s x(_), f(_), _      
    }.run
    
    sequence {
      fcvt_lu_s x(_), f(_), _      
      fcvt_lu_s x(_), f(_), _      
      fcvt_lu_s x(_), f(_), _      
      fcvt_lu_s x(_), f(_), _      
      fcvt_lu_s x(_), f(_), _      
    }.run
    
    sequence {
      mulw x(_), x(_), x(_)      
      mulw x(_), x(_), x(_)      
      mulw x(_), x(_), x(_)      
      mulw x(_), x(_), x(_)      
      mulw x(_), x(_), x(_)      
    }.run
    
    sequence {
      divw x(_), x(_), x(_)      
      divw x(_), x(_), x(_)      
      divw x(_), x(_), x(_)      
      divw x(_), x(_), x(_)      
      divw x(_), x(_), x(_)      
    }.run
    
    sequence {
      divuw x(_), x(_), x(_)      
      divuw x(_), x(_), x(_)      
      divuw x(_), x(_), x(_)      
      divuw x(_), x(_), x(_)      
      divuw x(_), x(_), x(_)      
    }.run
    
    sequence {
      remw x(_), x(_), x(_)      
      remw x(_), x(_), x(_)      
      remw x(_), x(_), x(_)      
      remw x(_), x(_), x(_)      
      remw x(_), x(_), x(_)      
    }.run
    
    sequence {
      remuw x(_), x(_), x(_)      
      remuw x(_), x(_), x(_)      
      remuw x(_), x(_), x(_)      
      remuw x(_), x(_), x(_)      
      remuw x(_), x(_), x(_)      
    }.run
    
    sequence {
      mul x(_), x(_), x(_)      
      mul x(_), x(_), x(_)      
      mul x(_), x(_), x(_)      
      mul x(_), x(_), x(_)      
      mul x(_), x(_), x(_)      
    }.run
    
    sequence {
      mulh x(_), x(_), x(_)      
      mulh x(_), x(_), x(_)      
      mulh x(_), x(_), x(_)      
      mulh x(_), x(_), x(_)      
      mulh x(_), x(_), x(_)      
    }.run
    
    sequence {
      mulhu x(_), x(_), x(_)      
      mulhu x(_), x(_), x(_)      
      mulhu x(_), x(_), x(_)      
      mulhu x(_), x(_), x(_)      
      mulhu x(_), x(_), x(_)      
    }.run
    
    sequence {
      mulhsu x(_), x(_), x(_)      
      mulhsu x(_), x(_), x(_)      
      mulhsu x(_), x(_), x(_)      
      mulhsu x(_), x(_), x(_)      
      mulhsu x(_), x(_), x(_)      
    }.run
    
    sequence {
      div x(_), x(_), x(_)      
      div x(_), x(_), x(_)      
      div x(_), x(_), x(_)      
      div x(_), x(_), x(_)      
      div x(_), x(_), x(_)      
    }.run
    
    sequence {
      divu x(_), x(_), x(_)      
      divu x(_), x(_), x(_)      
      divu x(_), x(_), x(_)      
      divu x(_), x(_), x(_)      
      divu x(_), x(_), x(_)      
    }.run
    
    sequence {
      rem x(_), x(_), x(_)      
      rem x(_), x(_), x(_)      
      rem x(_), x(_), x(_)      
      rem x(_), x(_), x(_)      
      rem x(_), x(_), x(_)      
    }.run
    
    sequence {
      remu x(_), x(_), x(_)      
      remu x(_), x(_), x(_)      
      remu x(_), x(_), x(_)      
      remu x(_), x(_), x(_)      
      remu x(_), x(_), x(_)      
    }.run
    
    #sequence {
    #  csrrw x(_), ustatus(), x(_)      
    #  csrrw x(_), ustatus(), x(_)      
    #  csrrw x(_), ustatus(), x(_)      
    #  csrrw x(_), ustatus(), x(_)      
    #  csrrw x(_), ustatus(), x(_)      
    #}.run
    #
    #sequence {
    #  csrrs x(_), ustatus(), x(_)      
    #  csrrs x(_), ustatus(), x(_)      
    #  csrrs x(_), ustatus(), x(_)      
    #  csrrs x(_), ustatus(), x(_)      
    #  csrrs x(_), ustatus(), x(_)      
    #}.run
    #
    #sequence {
    #  csrrc x(_), ustatus(), x(_)      
    #  csrrc x(_), ustatus(), x(_)      
    #  csrrc x(_), ustatus(), x(_)      
    #  csrrc x(_), ustatus(), x(_)      
    #  csrrc x(_), ustatus(), x(_)      
    #}.run
    #
    #sequence {
    #  csrrwi x(_), ustatus(), _      
    #  csrrwi x(_), ustatus(), _      
    #  csrrwi x(_), ustatus(), _      
    #  csrrwi x(_), ustatus(), _      
    #  csrrwi x(_), ustatus(), _      
    #}.run
    #
    #sequence {
    #  csrrsi x(_), ustatus(), _      
    #  csrrsi x(_), ustatus(), _      
    #  csrrsi x(_), ustatus(), _      
    #  csrrsi x(_), ustatus(), _      
    #  csrrsi x(_), ustatus(), _      
    #}.run
    #
    #sequence {
    #  csrrci x(_), ustatus(), _      
    #  csrrci x(_), ustatus(), _      
    #  csrrci x(_), ustatus(), _      
    #  csrrci x(_), ustatus(), _      
    #  csrrci x(_), ustatus(), _      
    #}.run
  end
end
